### ISSUE TITLE
add error handling

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_exporter#11]
e.g. for network timeouts, etc.

a few things i can think of are:
* some sort of error message to both the console and the `complete.log` output file.
* make sure that an error retrieving an individual resource doesn't cause the whole export attempt to fail
  * but make it clear that there was not full success and that some resources may be missing from the export.

spawned by #1

**Comment by justinlittman** [comment]
@jmartin-sul suggests that this is closable.

**Comment by jmartin-sul** [comment]
a little elaboration:
> some sort of error message to both the console and the `complete.log` output file.

console logging (and [honeybadger logging](#52)) are now both in place.  so we should be informed about errors when they occur, including timeouts and the sort of mis-handling described in #49.

> make sure that an error retrieving an individual resource doesn't cause the whole export attempt to fail

there is now more robust error handling than when this ticket was filed, and some `catch` statements have been added that should address this.
