### ISSUE TITLE
Exporter for all groups should create both a single folder with all groups and each group separately

### ISSUE THREAD

**Issue by peetucket** [LD4P/sinopia_exporter#159]
When run in all groups, currently the output of the exporter is a single containing directory and does not produce the output per group.  This appears to be by design right now, so if this is not correct, it's not clear how and when this behavior changed.

For example, if you run:

```
bin/export -a
```

You will get a single folder:

```
sinopia_export_all_2020-10-22T21:53:26.939Z
```

and not individual group folders.

This is because when the all group function sets up the common directory here: https://github.com/LD4P/sinopia_exporter/blob/master/src/exporter.js#L90

It then iterates over all the groups, and passes in this containing directory to the single group export function: https://github.com/LD4P/sinopia_exporter/blob/master/src/exporter.js#L102-L105

Since `containingDir` is not blank, the export will happen to that common folder for all groups that are iterated over.  

If we wanted to have the all groups export in both a single containing directory and separately, we would probably want to alter the single group export function so that if a `containingDir` is passed in, it makes a copy of the data there instead of just a single export, thus leaving two copies.

**Comment by michelleif** [comment]
status of this ticket? @jermnelson exporter seems to produce folder for each group currently. but not a single export of all. should we close this ticket? create new ticket for exporting all?

**Comment by jermnelson** [comment]
Since we still are not creating a single export for all of the groups; I think we should keep this ticket open until we do unless this feature is no longer desired.

**Comment by michelleif** [comment]
will make new ticket to request single export file
