### ISSUE TITLE
create export file of all resources

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_exporter#214]
we used to create an export file of all resources, along with export per group.

currently the exporter is only creating the group exports.

reinstate the single "all resources" export

**Comment by justinlittman** [comment]
Why?

**Comment by michelleif** [comment]
to use Sinopia data in another application.

**Comment by michelleif** [comment]
@justinlittman if API provides same function, i'm ok with not doing this.

**Comment by justinlittman** [comment]
The API does; if a user need appears, we can re-open.
