### ISSUE TITLE
exported JSON-LD is missing the resource's Trellis URI

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_exporter#53]
in the exported files we are producing and posting, the Trellis URI is missing

we need the Trellis URI because that's the thing's unique identifier

**Comment by justinlittman** [comment]
@timathom Do you have suggestions on how this should be encoded? The filename? A sameAs triple? Other?

**Comment by michelleif** [comment]
sorry I don't speak JSON-LD yet but I took an example and used JSON-LD Playground to convert to triples and get:
<https://json-ld.org/playground/> <http://id.loc.gov/ontologies/bibframe/content> <http://id.loc.gov/vocabulary/contentTypes/txt> .
<https://json-ld.org/playground/> <http://id.loc.gov/ontologies/bibframe/title> _:b0 .
<https://json-ld.org/playground/> <http://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bf2:Monograph:Work" .
<https://json-ld.org/playground/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Work> .
_:b0 <http://id.loc.gov/ontologies/bibframe/mainTitle> "beauty and the beast"@en .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .


so I thought what we were asking here is simply for the subject URI in each statement (which here becomes the playground URI) to be the Trellis URI of the resource

**Comment by timathom** [comment]
@michelleif That's what I assumed too. So, it would just be the Trellis URI as the `@id` value for the `@graph`, e.g.,

```
{
  "@graph": [
    {
      "@id": "https://trellis.development.sinopia.io/repository/yale/2d6dda8d-eb46-46e0-b1d7-f498eb59a6ed",
      "@type": [
        "http://www.loc.gov/mads/rdf/v1#ComplexSubject",
        "http://id.loc.gov/ontologies/bibframe/Topic"
      ],
      "http://sinopia.io/vocabulary/hasResourceTemplate": "Yale:RT:BF2:Topic",
      "http://www.loc.gov/mads/rdf/v1#componentList": {"@id": "_:fe03fa868b2aa4b1e86e9cdbb23e08cd2b1"}
    }
  ]
}
```

**Comment by justinlittman** [comment]
And that was my initial thought as well. However, what that is saying is NOT that https://trellis.development.sinopia.io/repository/yale/2d6dda8d-eb46-46e0-b1d7-f498eb59a6ed is the @id of the graph, but that it is the subject of the triples in that section.

That is, it is the subject of:
* has type "http://www.loc.gov/mads/rdf/v1#ComplexSubject"
* has type "http://id.loc.gov/ontologies/bibframe/Topic"
* "http://sinopia.io/vocabulary/hasResourceTemplate": "Yale:RT:BF2:Topic"
(Ignoring the #componentList for this example).

Note that @graph is an array. In a more complete example, there would be other sets of triples, each with an @id. Thus, what indicates the actual root resource is that the @id is "". Replacing that with the URI means that the root resource cannot be determined.

Do I have this right?

**Comment by timathom** [comment]
You're right, I misspoke--it's not the `@id` of the graph. The `@graph` is just a default (unnamed) graph. The `@id` URI represents the resource described using the Sinopia resource template. In N-Quads (as Michelle suggested):

```
<https://trellis.development.sinopia.io/repository/yale/2d6dda8d-eb46-46e0-b1d7-f498eb59a6ed> <http://sinopia.io/vocabulary/hasResourceTemplate> "Yale:RT:BF2:Topic" .
<https://trellis.development.sinopia.io/repository/yale/2d6dda8d-eb46-46e0-b1d7-f498eb59a6ed> <http://www.loc.gov/mads/rdf/v1#componentList> _:b0 .
<https://trellis.development.sinopia.io/repository/yale/2d6dda8d-eb46-46e0-b1d7-f498eb59a6ed> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Topic> .
<https://trellis.development.sinopia.io/repository/yale/2d6dda8d-eb46-46e0-b1d7-f498eb59a6ed> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.loc.gov/mads/rdf/v1#ComplexSubject> .
```

**Comment by justinlittman** [comment]
Per discussion with @timathom and @sfolsom, let's go with setting the `@id` of the root resource (which by default is `""`).
