### ISSUE TITLE
Handle resources that have URIs included

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_exporter#82]
The exporter currently assumes that all resources have relative URIs (<>), in which case it inserts the URI. The exporter should handle have resources that have relative URIs (<>) or already include the URI.

Related to https://github.com/ld4p/sinopia_editor/issues/1753

**Comment by mjgiarlo** [comment]
I would think that this code (only recently added to deal with null subjects) is already accommodating data with subject URIs: https://github.com/LD4P/sinopia_exporter/pull/70/files#diff-dbc2ddfc6efc5c676aa000e8abc942baR78-R80 This issue needs confirming before being ready.
